update README
keiyok/travel pull request #1
Opened 2022-07-29 23:00 UTC by keiyok

行き詰まってしまったので、
アドバイスを頂けるとありがたいです。

2022-07-30 05:51 UTC, keiyok commented
提出します

2022-07-30 10:24 UTC, TakuyaChida requested changes
内容を確認しました！

一通りの動作ができており、問題ありません！
素晴らしいです！

1点、ユーザ登録はできるのですが、その登録したユーザの編集機能が見当たらないようです。
※ユーザーのプロフィール（自己紹介、画像）が編集できるか
上記の要件が満たせていないようですので、追加修正をお願いいたします！

2022-07-30 10:24 UTC, TakuyaChida commented on app/controllers/rooms_controller.rb
> +    @room = Room.new(params.require(:room).permit(:title, :place, :content, :price, :image))
部屋の登録ができていますね。
合わせて金額などのバリデーションがあるとなお良いと思います！
例「正の数のみ」など

2022-07-30 10:24 UTC, TakuyaChida commented on app/controllers/reservations_controller.rb
> +    if @reservation.save
指定した部屋の予約ができていますね。
合わせて予約日数と人数の合計で合計金額などが表示できると良いです。

2022-07-30 10:24 UTC, TakuyaChida commented on app/controllers/rooms_controller.rb
> +    @rooms = Room.search(params[:keyword])
登録した部屋の検索ができていますね。
良いと思います！

2022-07-30 10:24 UTC, TakuyaChida commented on app/controllers/rooms_controller.rb
> +    @rooms = Room.all
一覧表示ができていますね。
問題ありません！

2022-07-30 10:24 UTC, TakuyaChida commented on app/controllers/reservations_controller.rb
> +    @reservations = Reservation.all
一覧表示ができていますね。
問題ありません！

2022-08-02 09:03 UTC, YamanakaSayaka commented on app/helpers/reservations_helper.rb
> +module ReservationsHelper
不要なヘルパーファイルは削除してOKです

2022-08-02 09:05 UTC, YamanakaSayaka commented on app/views/reservations/index.html.erb
> +</div>
行末は改行コードをいれるのが慣習になっています。このファイルだけではないのですが、挿入されていないので警告がでています。（㊀マーク）エディタのプラグインによって自動挿入してくれる機能もありますので調べてみてください。https://bottoms-programming.com/archives/indent-tab-space-and-new-line.html

2022-08-02 09:06 UTC, YamanakaSayaka commented on app/views/layouts/application.html.erb
> +    <header>
ヘッダーもパーシャル化することが多いです。最終課題では意識してみてください。

2022-08-02 09:06 UTC, YamanakaSayaka commented on app/views/reservations/_form.html.erb
> +<%= form_for([@room, @room.reservations.new]) do |f| %>
form_forではなく、form_withを使用しましょう。

2022-08-19 01:14 UTC, keiyok commented
あああ

2022-08-21 11:54 UTC, merged